start_pairing:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: elro_connects_k2
    timeout:
      required: false
      default: 60
      selector:
        number:
          min: 10
          max: 300
          step: 10
          unit_of_measurement: seconds
          mode: box

cancel_pairing:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: elro_connects_k2
